### ISSUE TITLE
Unable to open connction

### ISSUE THREAD

**Issue by jonaharndt** [Gazer29/JMRIswitches#7]
Unable to open connection from in game, verified web server is running, firewall is allowed, etc

**Comment by Quackers29** [comment]
I am hoping the Opencomputers config file settings is the problem here as I didn't state it in the instructions,
The config file is located: minecraft\config\opencomputers\settings.conf

Could you please check your Opencomputers config file settings for:
blacklist - If using a localhost connection, by default the config will have localhost on the blacklist and will need to be removed.
enableHttp = true.
enableHttpHeaders = true.
requestTimeout = 1, This stops the requests waiting forever.

The settings I used is below:

![image](https://user-images.githubusercontent.com/11053436/141695928-c6f0efd8-3c6c-47f2-8a7b-55afe08ddfe5.png)

**Comment by jonaharndt** [comment]
Thank you so much! I got everything to work! Such an amazing script you
made!

**Comment by Quackers29** [comment]
Thanks for testing out the installation and reporting it 👍

All thanks really to the Automation Mod which adds a tun of possibilities, the mod's discord link is below if you want to chat about ideas etc:  
https://discord.gg/PCxBNmcM
